from enum import Enum


class Status(Enum):
    WAITING = "WAITING"
    IN_SORTING = "IN_SORTING"
    THROWING_CARDS = "THROWING_CARDS"
    IN_GAME = "IN_GAME"
    ROUND_FINISHED = "ROUND_FINISHED"
    GAME_FINISHED = "GAME_FINISHED"
